blank_issues_enabled: false
contact_links:
  - name: Community Chat
    url: https://discord.gg/6VN6zTPZAy
    about: Ask and discuss real-time with other users on the unifyPreset channel on the UnifyUI Community's server.
